version: '3.5'
services:
 pgsql-server:
  image: timescale/timescaledb:2.3.1-pg13
  networks:
   - zbx_net
  environment:
   - POSTGRES_USER=zabbix
   - POSTGRES_DB=zabbixdb
   - POSTGRES_PASSWORD=Temporal01
   - ZBX_JAVAGATEWAY=zabbix-java-gateway
  volumes:
   - ./zabbix-data/pgsql:/var/lib/pgsql:rw
 zabbix-server-pgsql:
  image: zabbix/zabbix-server-pgsql:6.0.2-ol
  networks:
   - zbx_net
  ports:
   - 10051:10051
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ./zabbix-data/server/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zabbix-data/server/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zabbix-data/server/export:/var/lib/zabbix/export:rw
   - ./zabbix-data/server/modules:/var/lib/zabbix/modules:ro
   - ./zabbix-data/server/enc:/var/lib/zabbix/enc:ro
   - ./zabbix-data/server/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zabbix-data/server/mibs:/var/lib/zabbix/mibs:ro
   - ./zabbix-data/server/snmptraps:/var/lib/zabbix/snmptraps:rw
  environment:
   - DB_SERVER_HOST=pgsql-server
   - POSTGRES_DB=zabbixdb
   - POSTGRES_USER=zabbix
   - POSTGRES_PASSWORD=Temporal01
   - ZBX_JAVAGATEWAY=zabbix-java-gateway
  depends_on:
   - pgsql-server
 zabbix-web-nginx-pgsql:
  image: zabbix/zabbix-web-nginx-pgsql:6.0.2-alpine
  networks:
   - zbx_net
  ports:
   - 80:8080
   - 443:8443
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zabbix-data/nginx/:/etc/ssl/nginx:ro
   - ./zabbix-data/nginx/modules/:/usr/share/zabbix/modules/:ro
  environment:
   - ZBX_SERVER_HOST=zabbix-server-pgsql
   - DB_SERVER_HOST=pgsql-server
   - POSTGRES_DB=zabbixdb
   - POSTGRES_USER=zabbix
   - POSTGRES_PASSWORD=Temporal01
  depends_on:
   - pgsql-server
   - zabbix-server-pgsql
 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:alpine-6.0-latest
  networks:
   - zbx_net
  ports:
   - 10052:10052
networks:
 zbx_net:
   driver: bridge
